language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: rU9lNAFWwyC9dEWcg9KTx6DoBdXOEM1iCkUIWFnzQoz3QYnZ2yidBhnzEMeGbEVkOqqOaTQUtB6q93WsOwTP7tgooWlWD4F7X64uoD/Ze4/q4lqfpP0wREQvakbb1+cv//LAbzDDvmKkkMF+UFNfzDKDMGCGaQGPhfMxYH0Dtu5fo1ZLg1G0pM5FvV04qfsazHFK3zhgMOru292Z0njpFygsuqHqUP3G1yyA9cXYDCmNQUYTnqFl79b6HXGbMhZApisloqn7aetSFqIg/vx0fhY8MKQ1aD/4YvdMoaKnaW/LZdcXM/pHjKaOtitsWaNPefRx9c+8gguR4RHLjTBlBgGF0P0D0wSuz1X2oHrK69s7NhLxw+uc1AUmlNpMmROS1zJFsNBkiOpcVxvl92KRgHBtEo2vEQWv+aDyKPh01hjLsdgxlH6hVZj45zHwEam/mjnXRBD9MO9JX+cVl+XsE+7+jyq93sbnHq8HUqcddZqehanqG5TQirll7f6Rnkt0H8jpM57khm5t86gnBEAHfy7cX/oAZxIs5WM8uNLA/y4PGPPZ9ft6vOhrx18ALuaMO87sul6tnmO9F2qefd3FS4wToVNQyoj8w6aAOK4nqLdj0NFKFZYyPwpwm2G/cQ5P9K/37y/kJ0Z1TGbwn6+q0siRYqaBeon9qOvg2k49n7A=

branches:
  only:
  - dev

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="6"
  - WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="7"

matrix:
  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
    - node_modules
    - vendor

before_install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  - node -v
  # - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  # - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  # - sudo apt-get update -qq
  # - sudo apt-get install -y -qq yarn
  # - npm install -g cross-env

install:
  - composer install
  # - yarn

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
