dist: xenial
services:
- mysql
language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: rU9lNAFWwyC9dEWcg9KTx6DoBdXOEM1iCkUIWFnzQoz3QYnZ2yidBhnzEMeGbEVkOqqOaTQUtB6q93WsOwTP7tgooWlWD4F7X64uoD/Ze4/q4lqfpP0wREQvakbb1+cv//LAbzDDvmKkkMF+UFNfzDKDMGCGaQGPhfMxYH0Dtu5fo1ZLg1G0pM5FvV04qfsazHFK3zhgMOru292Z0njpFygsuqHqUP3G1yyA9cXYDCmNQUYTnqFl79b6HXGbMhZApisloqn7aetSFqIg/vx0fhY8MKQ1aD/4YvdMoaKnaW/LZdcXM/pHjKaOtitsWaNPefRx9c+8gguR4RHLjTBlBgGF0P0D0wSuz1X2oHrK69s7NhLxw+uc1AUmlNpMmROS1zJFsNBkiOpcVxvl92KRgHBtEo2vEQWv+aDyKPh01hjLsdgxlH6hVZj45zHwEam/mjnXRBD9MO9JX+cVl+XsE+7+jyq93sbnHq8HUqcddZqehanqG5TQirll7f6Rnkt0H8jpM57khm5t86gnBEAHfy7cX/oAZxIs5WM8uNLA/y4PGPPZ9ft6vOhrx18ALuaMO87sul6tnmO9F2qefd3FS4wToVNQyoj8w6aAOK4nqLdj0NFKFZYyPwpwm2G/cQ5P9K/37y/kJ0Z1TGbwn6+q0siRYqaBeon9qOvg2k49n7A=
branches:
  only:
  - dev
  - hotfix
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
php:
- 7.1
- 7.2
env:
- WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="10"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update || true
- sudo apt-get install -y default-jdk libxml2-utils ghostscript imagemagick poppler-utils unzip
- wget https://github.com/w3c/epubcheck/releases/download/v4.1.1/epubcheck-4.1.1.zip
- unzip epubcheck-4.1.1.zip -d /opt/
- mv /opt/epubcheck-4.1.1 /opt/epubcheck
- rm epubcheck-4.1.1.zip
- wget https://www.princexml.com/download/prince_12.5-1_ubuntu16.04_amd64.deb
- sudo dpkg -i prince_12.5-1_ubuntu16.04_amd64.deb
- rm prince_12.5-1_ubuntu16.04_amd64.deb
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install
- composer install
- ulimit -n 4096
before_script:
- if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
- pecl install pcov
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- npm run lint
- npm run build:production
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer require pcov/clobber; vendor/bin/pcov clobber; vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml; fi
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then vendor/bin/phpunit --configuration phpunit.xml; fi
- vendor/bin/phpcs --standard=phpcs.ruleset.xml *.php inc/ bin/
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GBpewhfS9/0xpsmCgIyAaU6SZq6aI35gpfgsZnf5nspb7NuKPmKwi+f/hBBXKg+gT96ZmoJiauaqsMsvSf1NDobzP4CxAp+yESVeXJCsUuOWaDJF0MCrqcFoGD1L3RXYiYsyIsX5zEwc+se8lAVCKTI5/z0RIIpPuFN/+TUZfySddUSKX3YOk0+TbLVajWlBxv7CMl55j7NklAEh5ygVY1uQFIpiMuRgTSMI0hE8HI4wMPuNgUNNkiX3zHmQiez2jmjdoyBfNQA5/4Nf0HnFzx3CkVaWAwmxlxdFCZEyK8axBrzb0FUJOCgfSF6ELjzN08Do1tGpsjtFklOMKVIaiC7l8fr+pigYpvrgcqLFfnfolRj5yiJxBoc4yvOsNzxXUvlnjlOpZ8t36+Q9UmIhe7RdbEb1NEHUyZtf5VerJg5lYnFqMlrK+DO2gSKT9ic01SHeJnKubJ53hAyMZtzJWWZd5ZAxlg7kd1VZOsehybhAbdTVB9lKjvCp2SoA1c+vSMrCsDW3jql7bvTsClfsJ6ohMp6DxC2V9YPQ19HUqFQr11yMde98Y8CeCgG8unvNO1nlDYH3STECJbGMAjqTHc2auvUathWzFI1l4iu1rpYvoMDbmssl8XouC1PWVrIvFgrO5XZ5sb+EluIDa+wwq/oLy9n3YH9FXOf9x360yFI=
  file: "pressbooks-$TRAVIS_TAG.zip"
  on:
    tags: true
    repo: pressbooks/pressbooks
