name: Update .mo files ğŸŒ

on:
  pull_request:
    branches: [dev]
    paths:
      - "languages/*.po"
  workflow_dispatch:

jobs:
  update-mo-files:
    uses: pressbooks/reusable-workflows/.github/workflows/update-mo.yml@main
